language: node_js
node_js:
  - node
env:
  global:
    - CC_TEST_REPORTER_ID=20137d97045791a6687be480b669551ce7ec5e8a2b217213416dc30fb7502c1a
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make lint
  - make test-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false