language: node_js
node_js:
  - node
env:
  global:
    - CC_TEST_REPORTER_ID=2df6168315337ed3fe658f89541ef6c91c2fbafd1d3f0c975986c55e23d7580e
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make lint
  - make test-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false